/// Arti Asmaul Husna per-locale (ID/MS/TR). EN diambil dari asma_data.dart.
///
/// Index 0 = nama #1 ... index 98 = nama #99. Urutan HARUS sama dengan asmaList.
String asmaMeaning(String locale, int number) {
  final i = number - 1;
  if (i < 0 || i >= 99) return '';
  switch (locale) {
    case 'ms':
      return _asmaMS[i];
    case 'tr':
      return _asmaTR[i];
    default:
      return _asmaID[i];
  }
}

const _asmaID = <String>[
  'Maha Pengasih',
  'Maha Penyayang',
  'Maha Raja',
  'Maha Suci',
  'Maha Sejahtera',
  'Maha Pemberi Keamanan',
  'Maha Pemelihara',
  'Maha Perkasa',
  'Maha Kuasa',
  'Maha Megah',
  'Maha Pencipta',
  'Maha Pembuat',
  'Maha Pembentuk',
  'Maha Pengampun',
  'Maha Penunduk',
  'Maha Pemberi',
  'Maha Pemberi Rezeki',
  'Maha Pembuka',
  'Maha Mengetahui',
  'Maha Penyempit',
  'Maha Pelapang',
  'Maha Perendah',
  'Maha Peninggi',
  'Maha Pemberi Kemuliaan',
  'Maha Penghina',
  'Maha Mendengar',
  'Maha Melihat',
  'Maha Hakim',
  'Maha Adil',
  'Maha Lembut',
  'Maha Waspada',
  'Maha Penyantun',
  'Maha Agung',
  'Maha Pengampun',
  'Maha Mensyukuri',
  'Maha Tinggi',
  'Maha Besar',
  'Maha Penjaga',
  'Maha Pemberi Kecukupan',
  'Maha Penghitung',
  'Maha Mulia',
  'Maha Dermawan',
  'Maha Mengawasi',
  'Maha Mengabulkan',
  'Maha Luas',
  'Maha Bijaksana',
  'Maha Mencintai',
  'Maha Mulia',
  'Maha Membangkitkan',
  'Maha Menyaksikan',
  'Maha Benar',
  'Maha Pelindung',
  'Maha Kuat',
  'Maha Kokoh',
  'Maha Pelindung',
  'Maha Terpuji',
  'Maha Menghitung',
  'Maha Memulai',
  'Maha Mengembalikan',
  'Maha Menghidupkan',
  'Maha Mematikan',
  'Maha Hidup',
  'Maha Berdiri Sendiri',
  'Maha Menemukan',
  'Maha Mulia',
  'Maha Esa',
  'Maha Tunggal',
  'Maha Dibutuhkan',
  'Maha Kuasa',
  'Maha Berkuasa',
  'Maha Mendahulukan',
  'Maha Mengakhirkan',
  'Maha Awal',
  'Maha Akhir',
  'Maha Nyata',
  'Maha Tersembunyi',
  'Maha Mengatur',
  'Maha Tinggi',
  'Maha Berbuat Baik',
  'Maha Penerima Taubat',
  'Maha Pembalas',
  'Maha Pemaaf',
  'Maha Penyayang',
  'Maha Pemilik Kerajaan',
  'Pemilik Keagungan dan Kemuliaan',
  'Maha Adil',
  'Maha Pengumpul',
  'Maha Kaya',
  'Maha Memberi Kekayaan',
  'Maha Mencegah',
  'Maha Pemberi Bahaya',
  'Maha Pemberi Manfaat',
  'Maha Cahaya',
  'Maha Pemberi Petunjuk',
  'Maha Pencipta Baru',
  'Maha Kekal',
  'Maha Pewaris',
  'Maha Bijaksana',
  'Maha Sabar',
];

const _asmaMS = <String>[
  'Maha Pengasih',
  'Maha Penyayang',
  'Maha Raja',
  'Maha Suci',
  'Maha Sejahtera',
  'Maha Pemberi Keamanan',
  'Maha Pemelihara',
  'Maha Perkasa',
  'Maha Kuasa',
  'Maha Megah',
  'Maha Pencipta',
  'Maha Pembuat',
  'Maha Pembentuk',
  'Maha Pengampun',
  'Maha Penunduk',
  'Maha Pemberi',
  'Maha Pemberi Rezeki',
  'Maha Pembuka',
  'Maha Mengetahui',
  'Maha Penyempit',
  'Maha Pelapang',
  'Maha Perendah',
  'Maha Peninggi',
  'Maha Pemberi Kemuliaan',
  'Maha Penghina',
  'Maha Mendengar',
  'Maha Melihat',
  'Maha Hakim',
  'Maha Adil',
  'Maha Lembut',
  'Maha Waspada',
  'Maha Penyantun',
  'Maha Agung',
  'Maha Pengampun',
  'Maha Mensyukuri',
  'Maha Tinggi',
  'Maha Besar',
  'Maha Penjaga',
  'Maha Pemberi Kecukupan',
  'Maha Penghitung',
  'Maha Mulia',
  'Maha Dermawan',
  'Maha Mengawasi',
  'Maha Mengabulkan',
  'Maha Luas',
  'Maha Bijaksana',
  'Maha Mencintai',
  'Maha Mulia',
  'Maha Membangkitkan',
  'Maha Menyaksikan',
  'Maha Benar',
  'Maha Pelindung',
  'Maha Kuat',
  'Maha Kokoh',
  'Maha Pelindung',
  'Maha Terpuji',
  'Maha Menghitung',
  'Maha Memulai',
  'Maha Mengembalikan',
  'Maha Menghidupkan',
  'Maha Mematikan',
  'Maha Hidup',
  'Maha Berdiri Sendiri',
  'Maha Menemukan',
  'Maha Mulia',
  'Maha Esa',
  'Maha Tunggal',
  'Maha Dibutuhkan',
  'Maha Kuasa',
  'Maha Berkuasa',
  'Maha Mendahulukan',
  'Maha Mengakhirkan',
  'Maha Awal',
  'Maha Akhir',
  'Maha Nyata',
  'Maha Tersembunyi',
  'Maha Mengatur',
  'Maha Tinggi',
  'Maha Berbuat Baik',
  'Maha Penerima Taubat',
  'Maha Pembalas',
  'Maha Pemaaf',
  'Maha Penyayang',
  'Maha Pemilik Kerajaan',
  'Pemilik Keagungan dan Kemuliaan',
  'Maha Adil',
  'Maha Pengumpul',
  'Maha Kaya',
  'Maha Memberi Kekayaan',
  'Maha Mencegah',
  'Maha Pemberi Bahaya',
  'Maha Pemberi Manfaat',
  'Maha Cahaya',
  'Maha Pemberi Petunjuk',
  'Maha Pencipta Baru',
  'Maha Kekal',
  'Maha Pewaris',
  'Maha Bijaksana',
  'Maha Sabar',
];

const _asmaTR = <String>[
  'Rahmân',
  'Rahîm',
  'Melik',
  'Kuddûs',
  'Selâm',
  "Mü'min",
  'Müheymin',
  'Azîz',
  'Cebbâr',
  'Mütekebbir',
  'Hâlık',
  'Bârî',
  'Musavvir',
  'Gaffâr',
  'Kahhâr',
  'Vehhâb',
  'Rezzâk',
  'Fettâh',
  'Alîm',
  'Kâbıd',
  'Bâsıt',
  'Hâfıd',
  "Râfi'",
  "Mu'ız",
  'Müzil',
  "Semî",
  'Basîr',
  'Hakem',
  'Adl',
  'Latîf',
  'Habîr',
  'Halîm',
  'Azîm',
  'Gafûr',
  'Şekûr',
  'Aliyy',
  'Kebîr',
  'Hafîz',
  'Mukît',
  'Hasîb',
  'Celîl',
  'Kerîm',
  'Rakîb',
  'Mücîb',
  "Vâsi",
  'Hakîm',
  'Vedûd',
  'Mecîd',
  "Bâ'is",
  'Şehîd',
  'Hakk',
  'Vekîl',
  'Kaviyy',
  'Metîn',
  'Veliyy',
  'Hamîd',
  'Muhsî',
  "Mübdi",
  "Mu'îd",
  'Muhyî',
  'Mümît',
  'Hayy',
  'Kayyûm',
  'Vâcid',
  'Mâcid',
  'Vâhid',
  'Ehad',
  'Samed',
  'Kâdir',
  'Muktedir',
  'Mukaddim',
  'Muahhir',
  'Evvel',
  'Âhir',
  'Zâhir',
  'Bâtın',
  'Vâlî',
  'Müteâlî',
  'Berr',
  'Tevvâb',
  'Müntekım',
  'Afüvv',
  "Ra'ûf",
  "Mâlikü'l-Mülk",
  "Zü'l-Celâli ve'l-İkrâm",
  'Muksıt',
  "Câmi'",
  'Ganiyy',
  'Muğnî',
  "Mâni'",
  'Dârr',
  "Nâfi'",
  'Nûr',
  'Hâdî',
  "Bedî'",
  'Bâkî',
  'Vâris',
  'Reşîd',
  'Sabûr',
];
