/// Data Asmaul Husna (99 nama Allah) — Arab + transliterasi universal.
///
/// Sumber Arab/transliterasi/EN: API Aladhan (api.aladhan.com/v1/asmaAlHusna).
/// Arti ID/MS/TR diterjemahkan dari EN (lihat asma_meanings.dart).
/// Disimpan lokal agar offline — tidak perlu fetch tiap buka.
class AsmaItem {
  final int number;
  final String arab;
  final String translit;
  final String meaningEn;
  const AsmaItem({required this.number, required this.arab, required this.translit, required this.meaningEn});
}

const asmaList = <AsmaItem>[
  AsmaItem(number: 1, arab: 'الرَّحْمَنُ', translit: 'Ar Rahmaan', meaningEn: 'The Beneficent'),
  AsmaItem(number: 2, arab: 'الرَّحِيمُ', translit: 'Ar Raheem', meaningEn: 'The Merciful'),
  AsmaItem(number: 3, arab: 'الْمَلِكُ', translit: 'Al Malik', meaningEn: 'The King / Eternal Lord'),
  AsmaItem(number: 4, arab: 'الْقُدُّوسُ', translit: 'Al Quddus', meaningEn: 'The Purest'),
  AsmaItem(number: 5, arab: 'السَّلاَمُ', translit: 'As Salaam', meaningEn: 'The Source of Peace'),
  AsmaItem(number: 6, arab: 'الْمُؤْمِنُ', translit: 'Al Mu\'min', meaningEn: 'The inspirer of faith'),
  AsmaItem(number: 7, arab: 'الْمُهَيْمِنُ', translit: 'Al Muhaymin', meaningEn: 'The Guardian'),
  AsmaItem(number: 8, arab: 'الْعَزِيزُ', translit: 'Al Azeez', meaningEn: 'The Precious / The Most Mighty'),
  AsmaItem(number: 9, arab: 'الْجَبَّارُ', translit: 'Al Jabbaar', meaningEn: 'The Compeller'),
  AsmaItem(number: 10, arab: 'الْمُتَكَبِّرُ', translit: 'Al Mutakabbir', meaningEn: 'The Greatest'),
  AsmaItem(number: 11, arab: 'الْخَالِقُ', translit: 'Al Khaaliq', meaningEn: 'The Creator'),
  AsmaItem(number: 12, arab: 'الْبَارِئُ', translit: 'Al Baari', meaningEn: 'The Maker of Order'),
  AsmaItem(number: 13, arab: 'الْمُصَوِّرُ', translit: 'Al Musawwir', meaningEn: 'The Shaper of Beauty'),
  AsmaItem(number: 14, arab: 'الْغَفَّارُ', translit: 'Al Ghaffaar', meaningEn: 'The Forgiving'),
  AsmaItem(number: 15, arab: 'الْقَهَّارُ', translit: 'Al Qahhaar', meaningEn: 'The Subduer'),
  AsmaItem(number: 16, arab: 'الْوَهَّابُ', translit: 'Al Wahhaab', meaningEn: 'The Giver of All'),
  AsmaItem(number: 17, arab: 'الرَّزَّاقُ', translit: 'Ar Razzaaq', meaningEn: 'The Sustainer'),
  AsmaItem(number: 18, arab: 'الْفَتَّاحُ', translit: 'Al Fattaah', meaningEn: 'The Opener'),
  AsmaItem(number: 19, arab: 'اَلْعَلِيْمُ', translit: 'Al \'Aleem', meaningEn: 'The Knower of all'),
  AsmaItem(number: 20, arab: 'الْقَابِضُ', translit: 'Al Qaabid', meaningEn: 'The Constrictor'),
  AsmaItem(number: 21, arab: 'الْبَاسِطُ', translit: 'Al Baasit', meaningEn: 'The Reliever'),
  AsmaItem(number: 22, arab: 'الْخَافِضُ', translit: 'Al Khaafid', meaningEn: 'The Abaser'),
  AsmaItem(number: 23, arab: 'الرَّافِعُ', translit: 'Ar Raafi\'', meaningEn: 'The Exalter'),
  AsmaItem(number: 24, arab: 'الْمُعِزُّ', translit: 'Al Mu\'iz', meaningEn: 'The Bestower of Honour'),
  AsmaItem(number: 25, arab: 'المُذِلُّ', translit: 'Al Mudhil', meaningEn: 'The Humiliator'),
  AsmaItem(number: 26, arab: 'السَّمِيعُ', translit: 'As Samee\'', meaningEn: 'The Hearer of all'),
  AsmaItem(number: 27, arab: 'الْبَصِيرُ', translit: 'Al Baseer', meaningEn: 'The Seer of all'),
  AsmaItem(number: 28, arab: 'الْحَكَمُ', translit: 'Al Hakam', meaningEn: 'The Judge'),
  AsmaItem(number: 29, arab: 'الْعَدْلُ', translit: 'Al \'Adl', meaningEn: 'The Just'),
  AsmaItem(number: 30, arab: 'اللَّطِيفُ', translit: 'Al Lateef', meaningEn: 'The Subtle One'),
  AsmaItem(number: 31, arab: 'الْخَبِيرُ', translit: 'Al Khabeer', meaningEn: 'The All Aware'),
  AsmaItem(number: 32, arab: 'الْحَلِيمُ', translit: 'Al Haleem', meaningEn: 'The Forebearing'),
  AsmaItem(number: 33, arab: 'الْعَظِيمُ', translit: 'Al \'Azeem', meaningEn: 'The Maginificent'),
  AsmaItem(number: 34, arab: 'الْغَفُورُ', translit: 'Al Ghafoor', meaningEn: 'The Great Forgiver'),
  AsmaItem(number: 35, arab: 'الشَّكُورُ', translit: 'Ash Shakoor', meaningEn: 'The Rewarder of Thankfulness'),
  AsmaItem(number: 36, arab: 'الْعَلِيُّ', translit: 'Al \'Aliyy', meaningEn: 'The Highest'),
  AsmaItem(number: 37, arab: 'الْكَبِيرُ', translit: 'Al Kabeer', meaningEn: 'The Greatest'),
  AsmaItem(number: 38, arab: 'الْحَفِيظُ', translit: 'Al Hafeez', meaningEn: 'The Preserver'),
  AsmaItem(number: 39, arab: 'المُقيِت', translit: 'Al Muqeet', meaningEn: 'The Nourisher'),
  AsmaItem(number: 40, arab: 'الْحسِيبُ', translit: 'Al Haseeb', meaningEn: 'The Reckoner'),
  AsmaItem(number: 41, arab: 'الْجَلِيلُ', translit: 'Al Jaleel', meaningEn: 'The Majestic'),
  AsmaItem(number: 42, arab: 'الْكَرِيمُ', translit: 'Al Kareem', meaningEn: 'The Generous'),
  AsmaItem(number: 43, arab: 'الرَّقِيبُ', translit: 'Ar Raqeeb', meaningEn: 'The Watchful One'),
  AsmaItem(number: 44, arab: 'الْمُجِيبُ', translit: 'Al Mujeeb ', meaningEn: 'The Responder to Prayer'),
  AsmaItem(number: 45, arab: 'الْوَاسِعُ', translit: 'Al Waasi\'', meaningEn: 'The All Comprehending'),
  AsmaItem(number: 46, arab: 'الْحَكِيمُ', translit: 'Al Hakeem', meaningEn: 'The Perfectly Wise'),
  AsmaItem(number: 47, arab: 'الْوَدُودُ', translit: 'Al Wudood', meaningEn: 'The Loving One'),
  AsmaItem(number: 48, arab: 'الْمَجِيدُ', translit: 'Al Majeed', meaningEn: 'The Most Glorious One'),
  AsmaItem(number: 49, arab: 'الْبَاعِثُ', translit: 'Al Baa\'ith', meaningEn: 'The Resurrector'),
  AsmaItem(number: 50, arab: 'الشَّهِيدُ', translit: 'Ash Shaheed', meaningEn: 'The Witness'),
  AsmaItem(number: 51, arab: 'الْحَقُّ', translit: 'Al Haqq', meaningEn: 'The Truth'),
  AsmaItem(number: 52, arab: 'الْوَكِيلُ', translit: 'Al Wakeel', meaningEn: 'The Trustee'),
  AsmaItem(number: 53, arab: 'الْقَوِيُّ', translit: 'Al Qawiyy', meaningEn: 'The Possessor of all strength'),
  AsmaItem(number: 54, arab: 'الْمَتِينُ', translit: 'Al Mateen', meaningEn: 'The Forceful'),
  AsmaItem(number: 55, arab: 'الْوَلِيُّ', translit: 'Al Waliyy', meaningEn: 'The Protector'),
  AsmaItem(number: 56, arab: 'الْحَمِيدُ', translit: 'Al Hameed', meaningEn: 'The Praised'),
  AsmaItem(number: 57, arab: 'الْمُحْصِي', translit: 'Al Muhsi', meaningEn: 'The Appraiser'),
  AsmaItem(number: 58, arab: 'الْمُبْدِئُ', translit: 'Al Mubdi', meaningEn: 'The Originator'),
  AsmaItem(number: 59, arab: 'الْمُعِيدُ', translit: 'Al Mu\'eed', meaningEn: 'The Restorer'),
  AsmaItem(number: 60, arab: 'الْمُحْيِي', translit: 'Al Muhiy', meaningEn: 'The Giver of life'),
  AsmaItem(number: 61, arab: 'اَلْمُمِيتُ', translit: 'Al Mumeet', meaningEn: 'The Taker of life'),
  AsmaItem(number: 62, arab: 'الْحَيُّ', translit: 'Al Haiyy', meaningEn: 'The Ever Living'),
  AsmaItem(number: 63, arab: 'الْقَيُّومُ', translit: 'Al Qayyoom', meaningEn: 'The Self Existing'),
  AsmaItem(number: 64, arab: 'الْوَاجِدُ', translit: 'Al Waajid', meaningEn: 'The Finder'),
  AsmaItem(number: 65, arab: 'الْمَاجِدُ', translit: 'Al Maajid', meaningEn: 'The Glorious'),
  AsmaItem(number: 66, arab: 'الْواحِدُ', translit: 'Al Waahid', meaningEn: 'The Only One'),
  AsmaItem(number: 67, arab: 'اَلاَحَدُ', translit: 'Al Ahad', meaningEn: 'The One'),
  AsmaItem(number: 68, arab: 'الصَّمَدُ', translit: 'As Samad', meaningEn: 'The Supreme Provider'),
  AsmaItem(number: 69, arab: 'الْقَادِرُ', translit: 'Al Qaadir', meaningEn: 'The Powerful'),
  AsmaItem(number: 70, arab: 'الْمُقْتَدِرُ', translit: 'Al Muqtadir', meaningEn: 'The Creator of all power'),
  AsmaItem(number: 71, arab: 'الْمُقَدِّمُ', translit: 'Al Muqaddim', meaningEn: 'The Expediter'),
  AsmaItem(number: 72, arab: 'الْمُؤَخِّرُ', translit: 'Al Mu’akhir', meaningEn: 'The Delayer'),
  AsmaItem(number: 73, arab: 'الأوَّلُ', translit: 'Al Awwal', meaningEn: 'The First'),
  AsmaItem(number: 74, arab: 'الآخِرُ', translit: 'Al Aakhir', meaningEn: 'The Last'),
  AsmaItem(number: 75, arab: 'الظَّاهِرُ', translit: 'Az Zaahir', meaningEn: 'The Manifest'),
  AsmaItem(number: 76, arab: 'الْبَاطِنُ', translit: 'Al Baatin', meaningEn: 'The Hidden'),
  AsmaItem(number: 77, arab: 'الْوَالِي', translit: 'Al Waali', meaningEn: 'The Governor'),
  AsmaItem(number: 78, arab: 'الْمُتَعَالِي', translit: 'Al Muta’ali', meaningEn: 'The Supreme One'),
  AsmaItem(number: 79, arab: 'الْبَرُّ', translit: 'Al Barr', meaningEn: 'The Doer of Good'),
  AsmaItem(number: 80, arab: 'التَّوَابُ', translit: 'At Tawwaab', meaningEn: 'The Guide to Repentence'),
  AsmaItem(number: 81, arab: 'الْمُنْتَقِمُ', translit: 'Al Muntaqim', meaningEn: 'The Avenger'),
  AsmaItem(number: 82, arab: 'العَفُوُّ', translit: 'Al Afuww', meaningEn: 'The Forgiver'),
  AsmaItem(number: 83, arab: 'الرَّؤُوفُ', translit: 'Ar Ra’oof', meaningEn: 'The Clement'),
  AsmaItem(number: 84, arab: 'مَالِكُ الْمُلْكِ', translit: 'Maalik Ul Mulk', meaningEn: 'The Owner / Soverign of All'),
  AsmaItem(number: 85, arab: 'ذُوالْجَلاَلِ وَالإكْرَامِ', translit: 'Dhu Al Jalaali Wa Al Ikraam', meaningEn: 'Possessor of Majesty and Bounty'),
  AsmaItem(number: 86, arab: 'الْمُقْسِطُ', translit: 'Al Muqsit', meaningEn: 'The Equitable One'),
  AsmaItem(number: 87, arab: 'الْجَامِعُ', translit: 'Al Jaami\'', meaningEn: 'The Gatherer'),
  AsmaItem(number: 88, arab: 'الْغَنِيُّ', translit: 'Al Ghaniyy', meaningEn: 'The Rich One'),
  AsmaItem(number: 89, arab: 'الْمُغْنِي', translit: 'Al Mughi', meaningEn: 'The Enricher'),
  AsmaItem(number: 90, arab: 'اَلْمَانِعُ', translit: 'Al Maani\'', meaningEn: 'The Preventer of harm'),
  AsmaItem(number: 91, arab: 'الضَّارَّ', translit: 'Ad Daaarr', meaningEn: 'The Creator of the harmful'),
  AsmaItem(number: 92, arab: 'النَّافِعُ', translit: 'An Naafi’', meaningEn: 'The Bestower of Benefits'),
  AsmaItem(number: 93, arab: 'النُّورُ', translit: 'An Noor', meaningEn: 'The Light'),
  AsmaItem(number: 94, arab: 'الْهَادِي', translit: 'Al Haadi', meaningEn: 'The Guider'),
  AsmaItem(number: 95, arab: 'الْبَدِيعُ', translit: 'Al Badi\'', meaningEn: 'The Originator'),
  AsmaItem(number: 96, arab: 'اَلْبَاقِي', translit: 'Al Baaqi', meaningEn: 'The Everlasting One'),
  AsmaItem(number: 97, arab: 'الْوَارِثُ', translit: 'Al Waarith', meaningEn: 'The Inhertior'),
  AsmaItem(number: 98, arab: 'الرَّشِيدُ', translit: 'Ar Rasheed', meaningEn: 'The Most Righteous Guide'),
  AsmaItem(number: 99, arab: 'الصَّبُورُ', translit: 'As Saboor', meaningEn: 'The Patient One'),
];
