#!/usr/bin/env python3
"""Jembatan Dart untuk arti surat + jenis wahyu (Makkiyah/Madaniyah).

Arti surat bukan string UI biasa: 114 nilai yang harus ikut bahasa aktif. Jadi
disimpan di ARB (`qs_meaning_1..114`, `qsRevelation{Meccan,Medinan}`) dan
diakses lewat switch di `lib/l10n/quran_texts.g.dart`.

Sumber nilai (idempoten — ARB yang sudah ada TIDAK ditimpa):
  * `qs_meaning_N` id  → `assets/quran/surahs.json` (Kemenag, same as app)
  * `qs_meaning_N` en  → `api.alquran.cloud/v1/surah` englishNameTranslation
                         (otoritatif, bukan terjemahan mesin)
  * tr/ms              → diisi `arb_ai` (terjemahan mesin dari id), lihat arb_ai.yaml

Skrip ini hanya menulis ARB + jembatan Dart. Jalankan:
    python3 tool/gen_quran_surah_arb.py [--bridge-only]
    flutter gen-l10n && flutter analyze
"""
import json
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API = 'https://api.alquran.cloud/v1/surah'
LOCALES = ('id', 'en', 'tr', 'ms')

# Jenis wahyu: istilah baku per bahasa, bukan terjemahan mesin.
REVELATION = {
    'Meccan': ('Makkiyah', 'Meccan', 'Mekkî', 'Makkiyah'),
    'Medinan': ('Madaniyah', 'Medinan', 'Medenî', 'Madaniyah'),
}


def api_meta():
    req = urllib.request.Request(API, headers={'User-Agent': 'muslim-leveling/1.0'})
    data = json.load(urllib.request.urlopen(req, timeout=40))['data']
    assert len(data) == 114, f'API balik {len(data)} surat, harus 114'
    assert [s['number'] for s in data] == list(range(1, 115)), 'nomor surat tidak urut'
    return data


def insert_arb(path, pairs):
    """Sisipkan key tanpa mengurutkan ulang file (diff kecil), idempoten."""
    raw = path.read_text()
    data = json.loads(raw)
    fresh = {k: v for k, v in pairs.items() if k not in data}
    if not fresh:
        return 0
    trimmed = raw.rstrip()
    assert trimmed.endswith('}'), 'ARB tidak berakhir dengan }'
    body = trimmed[:-1].rstrip()
    if not body.endswith(','):
        body += ','
    entries = [f'  {json.dumps(k, ensure_ascii=False)}: '
               f'{json.dumps(v, ensure_ascii=False)}' for k, v in fresh.items()]
    out = body + '\n' + ',\n'.join(entries) + '\n}\n'
    json.loads(out)
    path.write_text(out)
    return len(fresh)


def write_bridge():
    cases = '\n'.join(f'      {n} => l10n.qs_meaning_{n},' for n in range(1, 115))
    rev_cases = '\n'.join(
        f"      '{en}' || '{idn}' => l10n.qsRevelation{en}," if idn != en else
        f"      '{en}' => l10n.qsRevelation{en},"
        for en, (idn, *_rest) in REVELATION.items())
    dart = f'''// GENERATED by tool/gen_quran_surah_arb.py — JANGAN edit manual.
// Teks hidup di lib/l10n/app_<locale>.arb; ini cuma jembatan nomor → getter.

import 'app_localizations.dart';

/// Arti nama surat nomor [surahNumber] (1..114) dalam bahasa aktif.
///
/// ponytail: switch, bukan Map — getter ARB cuma bisa diakses sebagai anggota
/// bernama, jadi tabel runtime tidak mungkin. Bound dicek supaya nomor di luar
/// 1..114 balik '' daripada melempar.
String surahMeaning(AppL10n l10n, int surahNumber) => switch (surahNumber) {{
{cases}
      _ => '',
    }};

/// Jenis wahyu: 'Meccan'/'Medinan' dari API, atau 'Makkiyah'/'Madaniyah' dari
/// aset lama. Nilai tak dikenal dikembalikan apa adanya.
String surahRevelation(AppL10n l10n, String revelation) => switch (revelation) {{
{rev_cases}
      _ => revelation,
    }};
'''
    out = ROOT / 'lib/l10n/quran_texts.g.dart'
    out.write_text(dart)
    print(f'{out.relative_to(ROOT)}: 114 arti + {len(REVELATION)} jenis wahyu')


def main():
    if '--bridge-only' not in sys.argv:
        meta = api_meta()
        surahs = json.loads((ROOT / 'assets/quran/surahs.json').read_text())
        idn = {s['number']: s['meaning'] for s in surahs}
        en = {s['number']: s['englishNameTranslation'] for s in meta}
        assert len(idn) == 114, f'surahs.json cuma {len(idn)} surat'

        n_id = insert_arb(ROOT / 'lib/l10n/app_id.arb',
                          {f'qs_meaning_{n}': idn[n] for n in range(1, 115)})
        n_en = insert_arb(ROOT / 'lib/l10n/app_en.arb',
                          {f'qs_meaning_{n}': en[n] for n in range(1, 115)})
        for loc in LOCALES:
            insert_arb(ROOT / f'lib/l10n/app_{loc}.arb', {
                f'qsRevelation{k}': v[LOCALES.index(loc)]
                for k, v in REVELATION.items()})
        print(f'app_id.arb: +{n_id} arti   app_en.arb: +{n_en} arti')
    write_bridge()
    print('\nLangkah: flutter gen-l10n && flutter analyze')


if __name__ == '__main__':
    main()
