#!/usr/bin/env python3
"""Jembatan medali → l10n. TIDAK menyimpan terjemahan.

Sumber teks medali:
  - Indonesia : lib/services/achievement_service.dart (defs, fallback offline)
  - English   : lib/l10n/app_en.arb, key `ach_<id>_<title|desc|hint>`

Kenapa perlu jembatan: teks medali dicari dari `AchievementDef.id` saat render,
dan AppL10n tidak punya getter dinamis. Script ini meng-emit switch yang
memanggil getter AppL10n — jadi teks English hidup HANYA di ARB (tidak ada
salinan kedua di Dart), dan key ARB yang hilang = error compile, bukan
fallback senyap.

Pakai:
    python3 tool/gen_medal_arb.py            # validasi + generate
    python3 tool/gen_medal_arb.py --missing  # cetak key ARB yang kurang

Alur tambah medali: tambah AchievementDef → `--missing` → isi ARB → jalankan
tanpa flag → `flutter gen-l10n`. ARB tidak pernah ditulis script ini.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVICE = ROOT / 'lib/services/achievement_service.dart'
ARB = {'id': ROOT / 'lib/l10n/app_id.arb', 'en': ROOT / 'lib/l10n/app_en.arb'}
OUT = ROOT / 'lib/l10n/ach_texts.g.dart'

# Kunci map hasil parse → nama field di Dart.
FIELDS = {'id': 'id', 'title': 'title', 'desc': 'desc', 'hint': 'unlockHint'}
TEXT_FIELDS = ('title', 'desc', 'hint')


def parse_defs(src):
    """Tiap blok AchievementDef(...) via brace matching (regex naif salah:
    ada nested paren di dalam blok)."""
    out = []
    for m in re.finditer(r'AchievementDef\(', src):
        i = m.end()
        depth, j = 1, i
        while depth > 0 and j < len(src):
            if src[j] == '(':
                depth += 1
            elif src[j] == ')':
                depth -= 1
            j += 1
        body = src[i:j - 1]
        d = {}
        for name, dart_field in FIELDS.items():
            fm = re.search(rf"\b{dart_field}:\s*'((?:[^'\\]|\\.)*)'", body)
            if fm:
                d[name] = fm.group(1).replace("\\'", "'")
        if d.get('id') and d.get('title') and d.get('desc'):
            out.append(d)
    return out


def main():
    defs = parse_defs(SERVICE.read_text())
    ids = [d['id'] for d in defs]
    if len(set(ids)) != len(ids):
        sys.exit('id medali duplikat')
    if 'first_blood' not in ids:
        sys.exit('parser rusak: first_blood tidak ketemu')

    arb = {loc: json.loads(p.read_text()) for loc, p in ARB.items()}
    want = [f"ach_{d['id']}_{f}" for d in defs for f in TEXT_FIELDS if f in d]
    missing = {loc: [k for k in want if k not in a] for loc, a in arb.items()}

    if '--missing' in sys.argv or any(missing.values()):
        print(f'medali: {len(defs)} · key dibutuhkan: {len(want)}')
        for loc, keys in missing.items():
            print(f"  app_{loc}.arb: {'kurang ' + str(len(keys)) if keys else 'OK'}")
        for loc, keys in missing.items():
            if keys:
                print(f'\n--- tambahkan ke lib/l10n/app_{loc}.arb ---')
                for k in keys:
                    print(f'  "{k}": "",')
        if '--missing' not in sys.argv:
            sys.exit(1)
        return

    lines = [
        '// GENERATED by tool/gen_medal_arb.py — JANGAN edit manual.',
        '// Teks hidup di lib/l10n/app_<locale>.arb; ini cuma jembatan id → getter.',
        '',
        "import 'app_localizations.dart';",
        '',
        '/// Teks medali `id` untuk bahasa aktif. [field] = title | desc | hint.',
        '/// null kalau medali itu tidak punya teks untuk field tersebut.',
        'String? achText(AppL10n l10n, String id, String field) =>',
        "    switch ('$id.$field') {",
    ]
    for d in defs:
        for field in TEXT_FIELDS:
            if field in d:
                lines.append(
                    f"      '{d['id']}.{field}' => l10n.ach_{d['id']}_{field},")
    lines += ['      _ => null,', '    };', '']
    OUT.write_text('\n'.join(lines))
    print(f'medali: {len(defs)} · teks: {len(want)} · {OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
