#!/usr/bin/env python3
"""Jembatan quest → l10n. TIDAK menyimpan terjemahan.

Sumber teks:
  - id quest  : lib/services/game_service.dart (blok Quest(id:, desc:))
  - copy pool : kategori di bawah (struktur tetap: 7 kategori × 4 baris + haid 4)
  - English   : lib/l10n/app_en.arb, key `quest_<id>_desc`, `questCopy_<kat>_<n>`,
                `questHaid_<n>`
  - Indonesia : ARB juga (template app_id.arb), jadi teks tak lagi di Dart

Kenapa perlu jembatan: desc quest dicari dari `Quest.id` saat render, dan
AppL10n tidak punya getter dinamis. Switch yang di-emit memanggil getter
AppL10n — jadi key ARB yang hilang = error compile, bukan fallback senyap.

Pakai:
    python3 tool/gen_quest_arb.py            # validasi + generate
    python3 tool/gen_quest_arb.py --missing  # cetak key ARB yang kurang

Alur tambah quest: tambah Quest di game_service.dart → `--missing` → isi ARB
→ jalankan tanpa flag → `flutter gen-l10n`.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SERVICE = ROOT / 'lib/services/game_service.dart'
ARB = {'id': ROOT / 'lib/l10n/app_id.arb', 'en': ROOT / 'lib/l10n/app_en.arb'}
OUT = ROOT / 'lib/l10n/quest_texts.g.dart'

# Kategori quest → nama enum _QuestCategory di quest_claim_screen.dart.
CATEGORIES = ['sholat', 'sunnah', 'zikir', 'quran', 'hadis', 'fiveRings',
              'subuhIsya']
PER_CATEGORY = 4
HAID_COUNT = 4


def parse_quest_ids(src):
    """id quest dari blok Quest(id: ...). Diurutkan, dedup."""
    ids = re.findall(r"id: '(quest_[a-z0-9_]+)',", src)
    seen, out = set(), []
    for i in ids:
        if i not in seen:
            seen.add(i)
            out.append(i)
    return out


def needs_goal(arb_id, qid):
    """True kalau desc quest ini memakai placeholder {goal} di ARB."""
    v = arb_id.get(f'{qid}_desc')
    return isinstance(v, str) and '{goal}' in v


def main():
    src = SERVICE.read_text()
    qids = parse_quest_ids(src)
    if len(qids) < 15:
        sys.exit(f'parser rusak: cuma {len(qids)} quest id ketemu')
    if 'quest_subuh_tepat' not in qids:
        sys.exit('parser rusak: quest_subuh_tepat tidak ketemu')

    arb = {loc: json.loads(p.read_text()) for loc, p in ARB.items()}

    want = [f'{q}_desc' for q in qids]
    want += [f'questCopy_{c}_{n}' for c in CATEGORIES
             for n in range(1, PER_CATEGORY + 1)]
    want += [f'questHaid_{n}' for n in range(1, HAID_COUNT + 1)]
    missing = {loc: [k for k in want if k not in a] for loc, a in arb.items()}

    if '--missing' in sys.argv or any(missing.values()):
        print(f'quest: {len(qids)} · key dibutuhkan: {len(want)}')
        for loc, keys in missing.items():
            print(f"  app_{loc}.arb: {'kurang ' + str(len(keys)) if keys else 'OK'}")
        for loc, keys in missing.items():
            if keys:
                print(f'\n--- tambahkan ke lib/l10n/app_{loc}.arb ---')
                for k in keys:
                    print(f'  "{k}": "",')
        if '--missing' not in sys.argv:
            sys.exit(1)
        return

    goal_quests = [q for q in qids if needs_goal(arb['id'], q)]
    lines = [
        '// GENERATED by tool/gen_quest_arb.py — JANGAN edit manual.',
        '// Teks hidup di lib/l10n/app_<locale>.arb; ini jembatan id → getter.',
        '//',
        '// Key ARB yang hilang = error compile, bukan fallback senyap ke',
        '// Indonesia (itulah kenapa jembatan ini ada, bukan map runtime).',
        '',
        "import 'app_localizations.dart';",
        '',
    ]

    # Id SEMUA quest — dipakai guard tes supaya setiap id diperiksa, bukan
    # cuma 5 yang kebetulan ter-shuffle di pool hari ini (temuan negatif-kontrol:
    # menghapus satu case di switch tidak ketahuan kalau quest itu di luar pool).
    lines += [
        '/// Semua id quest yang punya desc di ARB.',
        'const questAllIds = <String>[',
    ]
    for q in qids:
        lines.append(f"  '{q}',")
    lines += ['];', '']

    # ── desc quest ──
    lines += [
        '/// Desc quest untuk bahasa aktif, dari `Quest.id`.',
        '/// null kalau id tidak dikenal (data quest lama dari disk).',
        'String? questDesc(AppL10n l10n, String id, {',
        '  required int zikirGoal,',
        '}) =>',
        '    switch (id) {',
    ]
    for q in qids:
        call = f'l10n.{q}_desc'
        if q in goal_quests:
            call += '(zikirGoal)'
        lines.append(f"      '{q}' => {call},")
    lines += ['      _ => null,', '    };', '']

    # ── copy pool ──
    lines += [
        '/// Copy dorongan pada layar klaim quest.',
        '/// [category] = nama `_QuestCategory` (quest_claim_screen.dart),',
        '/// [index] = pilihan round-robin per quest.id, [haid] = mode haid.',
        '/// Modulo dilakukan di sini supaya pemanggil tak perlu tahu panjang pool.',
        'String? questCopy(AppL10n l10n, String category, int index,',
        '    {bool haid = false}) {',
        '  if (haid) return _pick(_haidPool(l10n), index);',
        '  final pool = switch (category) {',
    ]
    for c in CATEGORIES:
        lines.append(f"    '{c}' => _copy{ c[0].upper() + c[1:]}(l10n),")
    lines += [
        '    _ => null,',
        '  };',
        '  return pool == null ? null : _pick(pool, index);',
        '}',
        '',
        '/// Panjang tiap pool copy — dijaga tes supaya [index] tidak keluar',
        '/// jangkauan kalau pool berubah panjang.',
        f'const questCopyPoolSize = {PER_CATEGORY};',
        '',
        'String _pick(List<String> pool, int index) =>',
        '    pool[index.abs() % pool.length];',
        '',
    ]
    for c in CATEGORIES:
        name = c[0].upper() + c[1:]
        lines.append(f'List<String> _copy{name}(AppL10n l) => [')
        for n in range(1, PER_CATEGORY + 1):
            lines.append(f'      l.questCopy_{c}_{n},')
        lines += ['    ];', '']
    lines.append('List<String> _haidPool(AppL10n l) => [')
    for n in range(1, HAID_COUNT + 1):
        lines.append(f'      l.questHaid_{n},')
    lines += ['    ];', '']

    OUT.write_text('\n'.join(lines))
    print(f'quest: {len(qids)} (goal-placeholder: {len(goal_quests)}) · '
          f'copy: {len(CATEGORIES)}x{PER_CATEGORY}+{HAID_COUNT} · '
          f'{OUT.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
