// GENERATED by tool/gen_ulama_hijri_arb.py — JANGAN edit manual.
// Teks hidup di lib/l10n/app_<locale>.arb; ini cuma jembatan index → getter.

import 'app_localizations.dart';

/// Semua kutipan ulama untuk bahasa aktif, urutan sama dengan
/// [ulamaQuoteTokens] di services/ulama_quotes.dart. Pemanggil memilih index
/// dengan [highlightIndex] supaya pilihan tetap deterministik per tanggal.
List<({String token, String text})> ulamaQuoteTexts(AppL10n l10n) => [
  (token: 'Ali bin Abi Thalib', text: l10n.uq_ulama_ilmu_itu_lebih_baik_daripada_harta_ilmu),
  (token: 'Ali bin Abi Thalib', text: l10n.uq_ulama_orang_berilmu_itu_hidup_walau_sudah_wafa),
  (token: 'Ali bin Abi Thalib', text: l10n.uq_ulama_jangan_melihat_siapa_yang_berbicara_tapi),
  (token: 'Ali bin Abi Thalib', text: l10n.uq_ulama_nilai_seseorang_diukur_dari_apa_yang_dia),
  (token: 'Umar bin Khattab', text: l10n.uq_ulama_hisablah_dirimu_sendiri_sebelum_kamu_dih),
  (token: 'Umar bin Khattab', text: l10n.uq_ulama_aku_tidak_pernah_menyesal_karena_diam_ta),
  (token: 'Umar bin Khattab', text: l10n.uq_ulama_kehormatanmu_adalah_agamamu_dan_harga_di),
  (token: 'Imam Syafi\'i', text: l10n.uq_ulama_waktu_itu_seperti_pedang_kalau_kamu_tida),
  (token: 'Imam Syafi\'i', text: l10n.uq_ulama_ilmu_bukanlah_yang_dihafal_tetapi_ilmu_a),
  (token: 'Imam Syafi\'i', text: l10n.uq_ulama_ilmu_itu_cahaya_dan_cahaya_allah_tidak_a),
  (token: 'Imam Syafi\'i', text: l10n.uq_ulama_barangsiapa_tidak_tahan_lelahnya_belajar),
  (token: 'Imam Malik', text: l10n.uq_ulama_aku_tidak_berhenti_belajar_sejak_aku_men),
  (token: 'Imam Malik', text: l10n.uq_ulama_aku_tidak_memberi_fatwa_sampai_aku_berta),
  (token: 'Imam Ahmad bin Hanbal', text: l10n.uq_ulama_manusia_lebih_membutuhkan_ilmu_daripada),
  (token: 'Imam Ahmad bin Hanbal', text: l10n.uq_ulama_aku_tidak_menulis_satu_hadis_pun_melaink),
  (token: 'Imam Abu Hanifah', text: l10n.uq_ulama_ilmu_tanpa_amal_seperti_pohon_tanpa_buah),
  (token: 'Hasan al-Bashri', text: l10n.uq_ulama_anak_adam_hanyalah_kumpulan_hari_hari_se),
  (token: 'Hasan al-Bashri', text: l10n.uq_ulama_barangsiapa_mengenal_allah_dia_akan_menc),
  (token: 'Hasan al-Bashri', text: l10n.uq_ulama_sesungguhnya_dunia_ini_hanya_sebentar_ja),
  (token: 'Umar bin Abdul Aziz', text: l10n.uq_ulama_jadikan_dunia_ini_cukup_berada_di_tangan),
  (token: 'Umar bin Abdul Aziz', text: l10n.uq_ulama_perbanyaklah_mengingat_mati_karena_itu_m),
  (token: 'Sufyan ats-Tsauri', text: l10n.uq_ulama_aku_tidak_mengobati_sesuatu_yang_lebih_b),
  (token: 'Sufyan ats-Tsauri', text: l10n.uq_ulama_ilmu_itu_untuk_diamalkan_kalau_tidak_dia),
  (token: 'Abdullah bin Mas\'ud', text: l10n.uq_ulama_diam_adalah_hikmah_tapi_sedikit_orang_ya),
  (token: 'Abdullah bin Mas\'ud', text: l10n.uq_ulama_sebaik_baik_hati_adalah_yang_dipenuhi_ra),
  (token: 'Ibnu Qayyim al-Jauziyyah', text: l10n.uq_ulama_tidak_ada_yang_lebih_bermanfaat_bagi_hat),
  (token: 'Ibnu Qayyim al-Jauziyyah', text: l10n.uq_ulama_hati_bisa_sakit_seperti_badan_sakit_dan),
  (token: 'Ibnu Qayyim al-Jauziyyah', text: l10n.uq_ulama_kesabaran_itu_cahaya_dengannya_jalan_yan),
  (token: 'Al-Ghazali', text: l10n.uq_ulama_ilmu_tanpa_amal_adalah_sia_sia_dan_amal),
  (token: 'Al-Ghazali', text: l10n.uq_ulama_kebahagiaan_bukan_pada_banyaknya_harta_t),
  (token: 'Al-Ghazali', text: l10n.uq_ulama_siapa_yang_menuntut_ilmu_semata_untuk_me),
  (token: 'Ibrahim bin Adham', text: l10n.uq_ulama_jaga_hatimu_karena_allah_melihat_bukan_h),
];

/// Semua token (nama tokoh) — dipakai guard supaya tidak ada yang terlewat.
const List<String> ulamaAllTokens = [
  'Ali bin Abi Thalib',
  'Ali bin Abi Thalib',
  'Ali bin Abi Thalib',
  'Ali bin Abi Thalib',
  'Umar bin Khattab',
  'Umar bin Khattab',
  'Umar bin Khattab',
  'Imam Syafi\'i',
  'Imam Syafi\'i',
  'Imam Syafi\'i',
  'Imam Syafi\'i',
  'Imam Malik',
  'Imam Malik',
  'Imam Ahmad bin Hanbal',
  'Imam Ahmad bin Hanbal',
  'Imam Abu Hanifah',
  'Hasan al-Bashri',
  'Hasan al-Bashri',
  'Hasan al-Bashri',
  'Umar bin Abdul Aziz',
  'Umar bin Abdul Aziz',
  'Sufyan ats-Tsauri',
  'Sufyan ats-Tsauri',
  'Abdullah bin Mas\'ud',
  'Abdullah bin Mas\'ud',
  'Ibnu Qayyim al-Jauziyyah',
  'Ibnu Qayyim al-Jauziyyah',
  'Ibnu Qayyim al-Jauziyyah',
  'Al-Ghazali',
  'Al-Ghazali',
  'Al-Ghazali',
  'Ibrahim bin Adham',
];

/// Nama bulan Hijriah index 1..12 (index 0 kosong, mengikuti sumber lama).
String hijriMonthName(AppL10n l10n, int month) => switch (month) {
      1 => l10n.uq_month_1,
      2 => l10n.uq_month_2,
      3 => l10n.uq_month_3,
      4 => l10n.uq_month_4,
      5 => l10n.uq_month_5,
      6 => l10n.uq_month_6,
      7 => l10n.uq_month_7,
      8 => l10n.uq_month_8,
      9 => l10n.uq_month_9,
      10 => l10n.uq_month_10,
      11 => l10n.uq_month_11,
      12 => l10n.uq_month_12,
      _ => '',
    };

/// Label tanggal penting Hijriah; null kalau (bulan, hari) tidak terdaftar.
String? hijriEventLabel(AppL10n l10n, int month, int day) =>
    switch ((month, day)) {
      (1, 1) => l10n.uq_ev_1_1,
      (1, 10) => l10n.uq_ev_1_10,
      (3, 12) => l10n.uq_ev_3_12,
      (7, 27) => l10n.uq_ev_7_27,
      (8, 15) => l10n.uq_ev_8_15,
      (9, 1) => l10n.uq_ev_9_1,
      (9, 17) => l10n.uq_ev_9_17,
      (10, 1) => l10n.uq_ev_10_1,
      (12, 9) => l10n.uq_ev_12_9,
      (12, 10) => l10n.uq_ev_12_10,
      _ => null,
    };

/// Tanggal Hijriah lengkap: "17 Safar 1448 H" (id) / "17 Safar 1448 AH" (en).
String hijriDateLabel(AppL10n l10n, int day, int month, int year) =>
    '$day ${hijriMonthName(l10n, month)} $year ${l10n.hjHijriSuffix}';
