// GENERATED by tool/gen_quest_arb.py — JANGAN edit manual.
// Teks hidup di lib/l10n/app_<locale>.arb; ini jembatan id → getter.
//
// Key ARB yang hilang = error compile, bukan fallback senyap ke
// Indonesia (itulah kenapa jembatan ini ada, bukan map runtime).

import 'app_localizations.dart';

/// Semua id quest yang punya desc di ARB.
const questAllIds = <String>[
  'quest_subuh_tepat',
  'quest_five_rings',
  'quest_timely_prayers',
  'quest_dhuha_before_dzuhur',
  'quest_rawatib_two',
  'quest_dzuhur_tepat',
  'quest_maghrib_tepat',
  'quest_isya_hadir',
  'quest_any_three',
  'quest_subuh_isya',
  'quest_one_sunnah',
  'quest_rawatib_one',
  'quest_zikir_33',
  'quest_zikir_goal',
  'quest_quran_10ayat',
  'quest_hadis_3',
  'quest_dzikir_33_subuh',
  'quest_quran_1halaman',
  'quest_hadis_5',
  'quest_berjamaah_1',
  'quest_hero_streak_7',
];

/// Desc quest untuk bahasa aktif, dari `Quest.id`.
/// null kalau id tidak dikenal (data quest lama dari disk).
String? questDesc(AppL10n l10n, String id, {required int zikirGoal}) =>
    switch (id) {
      'quest_subuh_tepat' => l10n.quest_subuh_tepat_desc,
      'quest_five_rings' => l10n.quest_five_rings_desc,
      'quest_timely_prayers' => l10n.quest_timely_prayers_desc,
      'quest_dhuha_before_dzuhur' => l10n.quest_dhuha_before_dzuhur_desc,
      'quest_rawatib_two' => l10n.quest_rawatib_two_desc,
      'quest_dzuhur_tepat' => l10n.quest_dzuhur_tepat_desc,
      'quest_maghrib_tepat' => l10n.quest_maghrib_tepat_desc,
      'quest_isya_hadir' => l10n.quest_isya_hadir_desc,
      'quest_any_three' => l10n.quest_any_three_desc,
      'quest_subuh_isya' => l10n.quest_subuh_isya_desc,
      'quest_one_sunnah' => l10n.quest_one_sunnah_desc,
      'quest_rawatib_one' => l10n.quest_rawatib_one_desc,
      'quest_zikir_33' => l10n.quest_zikir_33_desc,
      'quest_zikir_goal' => l10n.quest_zikir_goal_desc(zikirGoal),
      'quest_quran_10ayat' => l10n.quest_quran_10ayat_desc,
      'quest_hadis_3' => l10n.quest_hadis_3_desc,
      'quest_dzikir_33_subuh' => l10n.quest_dzikir_33_subuh_desc,
      'quest_quran_1halaman' => l10n.quest_quran_1halaman_desc,
      'quest_hadis_5' => l10n.quest_hadis_5_desc,
      'quest_berjamaah_1' => l10n.quest_berjamaah_1_desc,
      'quest_hero_streak_7' => l10n.quest_hero_streak_7_desc,
      _ => null,
    };

/// Copy dorongan pada layar klaim quest.
/// [category] = nama `_QuestCategory` (quest_claim_screen.dart),
/// [index] = pilihan round-robin per quest.id, [haid] = mode haid.
/// Modulo dilakukan di sini supaya pemanggil tak perlu tahu panjang pool.
String? questCopy(
  AppL10n l10n,
  String category,
  int index, {
  bool haid = false,
}) {
  if (haid) return _pick(_haidPool(l10n), index);
  final pool = switch (category) {
    'sholat' => _copySholat(l10n),
    'sunnah' => _copySunnah(l10n),
    'zikir' => _copyZikir(l10n),
    'quran' => _copyQuran(l10n),
    'hadis' => _copyHadis(l10n),
    'fiveRings' => _copyFiveRings(l10n),
    'subuhIsya' => _copySubuhIsya(l10n),
    _ => null,
  };
  return pool == null ? null : _pick(pool, index);
}

/// Panjang tiap pool copy — dijaga tes supaya [index] tidak keluar
/// jangkauan kalau pool berubah panjang.
const questCopyPoolSize = 4;

String _pick(List<String> pool, int index) => pool[index.abs() % pool.length];

List<String> _copySholat(AppL10n l) => [
  l.questCopy_sholat_1,
  l.questCopy_sholat_2,
  l.questCopy_sholat_3,
  l.questCopy_sholat_4,
];

List<String> _copySunnah(AppL10n l) => [
  l.questCopy_sunnah_1,
  l.questCopy_sunnah_2,
  l.questCopy_sunnah_3,
  l.questCopy_sunnah_4,
];

List<String> _copyZikir(AppL10n l) => [
  l.questCopy_zikir_1,
  l.questCopy_zikir_2,
  l.questCopy_zikir_3,
  l.questCopy_zikir_4,
];

List<String> _copyQuran(AppL10n l) => [
  l.questCopy_quran_1,
  l.questCopy_quran_2,
  l.questCopy_quran_3,
  l.questCopy_quran_4,
];

List<String> _copyHadis(AppL10n l) => [
  l.questCopy_hadis_1,
  l.questCopy_hadis_2,
  l.questCopy_hadis_3,
  l.questCopy_hadis_4,
];

List<String> _copyFiveRings(AppL10n l) => [
  l.questCopy_fiveRings_1,
  l.questCopy_fiveRings_2,
  l.questCopy_fiveRings_3,
  l.questCopy_fiveRings_4,
];

List<String> _copySubuhIsya(AppL10n l) => [
  l.questCopy_subuhIsya_1,
  l.questCopy_subuhIsya_2,
  l.questCopy_subuhIsya_3,
  l.questCopy_subuhIsya_4,
];

List<String> _haidPool(AppL10n l) => [
  l.questHaid_1,
  l.questHaid_2,
  l.questHaid_3,
  l.questHaid_4,
];
